// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYOnWR84QBaVTkojA0RI0sQ_Aqq_l8lx8',
    appId: '1:1028120627771:web:36027a93d54012feea2a1e',
    messagingSenderId: '1028120627771',
    projectId: 'care-link-5538e',
    authDomain: 'care-link-5538e.firebaseapp.com',
    storageBucket: 'care-link-5538e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj6a9KrT6lumb1JnUC4d8s0UY7fQ4r1Rg',
    appId: '1:1028120627771:android:6cc9f549a0edef03ea2a1e',
    messagingSenderId: '1028120627771',
    projectId: 'care-link-5538e',
    storageBucket: 'care-link-5538e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFjV_SmuNzWHsTmZTWrJdIauLkUgACfF8',
    appId: '1:1028120627771:ios:8749d2d89b38b627ea2a1e',
    messagingSenderId: '1028120627771',
    projectId: 'care-link-5538e',
    storageBucket: 'care-link-5538e.firebasestorage.app',
    iosBundleId: 'com.example.careLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFjV_SmuNzWHsTmZTWrJdIauLkUgACfF8',
    appId: '1:1028120627771:ios:8749d2d89b38b627ea2a1e',
    messagingSenderId: '1028120627771',
    projectId: 'care-link-5538e',
    storageBucket: 'care-link-5538e.firebasestorage.app',
    iosBundleId: 'com.example.careLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYOnWR84QBaVTkojA0RI0sQ_Aqq_l8lx8',
    appId: '1:1028120627771:web:b6f2b9f2093910a7ea2a1e',
    messagingSenderId: '1028120627771',
    projectId: 'care-link-5538e',
    authDomain: 'care-link-5538e.firebaseapp.com',
    storageBucket: 'care-link-5538e.firebasestorage.app',
  );
}
